"""
-------------------------------------------------------
[program description]
-------------------------------------------------------
Author:  Kieran Mochrie
ID:      169048254
Email:   moch8254@mylaurier.ca
__updated__ = "2025-11-11"
-------------------------------------------------------
"""
# Imports
import tkinter as tk
from tkinter import messagebox
from tkinter import simpledialog
import os
import mysql.connector
import re
import sys
# python C:\Users\kiera\eclipse2\ws\CP363Assgn6\src\GUI.py
# Constants
queries = "dental_clinic_dbms_queries_a4.sql"
schema = "dental_clinic_dbms_a4.sql"
# Configure these for your setup
host = "localhost"
user = "root"
pWord = "Douggiemann05"   # change for uploaded verions
name = "dental_clinic_dbms_a4"
userFriendly = {  # list of queries and the user friendly names
    "1": {
        "title": "Find total revenue generated by each dentist (completed appointments)",
        "sql": """SELECT d.Dentist_Name, SUM(b.Bill_Total) AS Total_Revenue, COUNT(b.Bill_ID) AS Total_Bills
                  FROM billing b
                  JOIN appointment a ON b.Appointment_Info = a.Appointment_ID
                  JOIN dentist d ON a.Appointment_Dentist = d.Dentist_ID
                  WHERE b.Bill_Status = 'Y'
                  GROUP BY d.Dentist_ID
                  ORDER BY Total_Revenue DESC;"""
    },
    "2": {
        "title": "Compare total billed amount per patient with insurance coverage",
        "sql": """SELECT p.Patient_Name, i.Insurance_Name, SUM(b.Bill_Total) AS Total_Spent
                  FROM billing b
                  JOIN patient p ON b.Patient_ID = p.Patient_ID
                  JOIN insurance i ON p.Patient_Insurance_ID = i.Insurance_ID
                  GROUP BY p.Patient_ID, i.Insurance_Name
                  HAVING Total_Spent > 0
                  ORDER BY Total_Spent DESC;"""
    },
    "3": {
        "title": "Compute average, min, and max cost for treatments performed",
        "sql": """SELECT t.Treatment_Name, COUNT(tr.Record_ID) AS Num_Performed,
                  ROUND(AVG(t.Treatment_Cost), 2) AS Avg_Cost,
                  MIN(t.Treatment_Cost) AS Min_Cost,
                  MAX(t.Treatment_Cost) AS Max_Cost
                  FROM treatment_records tr
                  JOIN treatment t ON tr.Treatment_Info = t.Treatment_ID
                  GROUP BY t.Treatment_Name
                  ORDER BY Avg_Cost DESC;"""
    },
    "4": {
        "title": "Find patients treated by the same dentist in more than one appointment",
        "sql": """SELECT d.Dentist_Name, p.Patient_Name, COUNT(a.Appointment_ID) AS Visits
                  FROM appointment a
                  JOIN dentist d ON a.Appointment_Dentist = d.Dentist_ID
                  JOIN patient p ON a.Appointment_Patient = p.Patient_ID
                  GROUP BY d.Dentist_Name, p.Patient_Name
                  HAVING Visits > 1;"""
    },
    "5": {
        "title": "List dental assistants whose salary is above the clinic’s average",
        "sql": """SELECT Assistant_Name, Assistant_Salary
                  FROM dental_assistant
                  WHERE Assistant_Salary > (SELECT AVG(Assistant_Salary) FROM dental_assistant)
                  ORDER BY Assistant_Salary DESC;"""
    },
    "6": {
        "title": "List all patients, marking whether they have appointments",
        "sql": """SELECT p.Patient_Name, 'Has Appointment' AS Status
                  FROM patient p
                  JOIN appointment a ON p.Patient_ID = a.Appointment_Patient
                  UNION
                  SELECT p.Patient_Name, 'No Appointment' AS Status
                  FROM patient p
                  WHERE p.Patient_ID NOT IN (SELECT Appointment_Patient FROM appointment)
                  ORDER BY Patient_Name;"""
    },
    "7": {
        "title": "Assistants in appointments with treatments more expensive than the clinic’s average",
        "sql": """SELECT DISTINCT da.Assistant_Name, t.Treatment_Name, t.Treatment_Cost
                  FROM dental_assistant da
                  JOIN appointment_assistant aa ON da.Assistant_ID = aa.Assistant_ID
                  JOIN appointment a ON aa.Appointment_ID = a.Appointment_ID
                  JOIN treatment_records tr ON a.Appointment_ID = tr.Appointment_Information
                  JOIN treatment t ON tr.Treatment_Info = t.Treatment_ID
                  WHERE t.Treatment_Cost > (SELECT AVG(Treatment_Cost) FROM treatment)
                  ORDER BY t.Treatment_Cost DESC;"""
    },
    "8": {
        "title": "Average bill total per appointment for each dentist",
        "sql": """SELECT d.Dentist_Name, AVG(b.Bill_Total) AS Avg_Bill, COUNT(a.Appointment_ID) AS Num_Appointments
                  FROM billing b
                  JOIN appointment a ON b.Appointment_Info = a.Appointment_ID
                  JOIN dentist d ON a.Appointment_Dentist = d.Dentist_ID
                  GROUP BY d.Dentist_Name;"""
    },
    "9": {
        "title": "Patients who spent more than the average bill amount across the entire clinic",
        "sql": """SELECT p.Patient_Name, SUM(b.Bill_Total) AS Total_Spent
                  FROM billing b
                  JOIN patient p ON b.Patient_ID = p.Patient_ID
                  GROUP BY p.Patient_ID
                  HAVING Total_Spent > (SELECT AVG(Bill_Total) FROM billing)
                  ORDER BY Total_Spent DESC;"""
    },
    "10": {
        "title": "Show all views",
        "sql": "SHOW FULL TABLES WHERE Table_type = 'VIEW';"
    }
}


def dbConnect():
    return mysql.connector.connect(
        host=host,
        user=user,
        password=pWord,  # connec to database with this
        database=name,
        use_pure=True
    )


def userGUI():
    connection = dbConnect()  # connect to database
    # run these files to populate tables and have answers ready
    runFile(schema, connection)
    runFile(queries, connection)  # optional
    connection.close()  # close and re-open for user
    connection = dbConnect()

    # command and table lists
    commands = ["Display Tables", "1", "Display Query Options", "2", "Create New Table",
                "3", "Update Table", "4", "Delete Table", "5", "Exit Program", "6"]
    tables = ["appointment", "appointment_assistant", "billing",
              "dental_assistant", "dentist", "dentist_performance",
              "insurance", "medicine", "patient", "prescription",
              "prescription_medicine", "treatment", "treatment_records",
              "v_high_spending_patients"]

    def getCommand():
        user_input = entry_widget.get().strip()

        if user_input not in commands:
            messagebox.showerror(
                "Invalid Command", "Please Enter a Valid Command (1–6) or a Command Name.")
            entry_widget.delete(0, tk.END)
            return

        # Clear entry box
        entry_widget.delete(0, tk.END)

        # Handle valid commands
        if user_input == "1":  # Display Tables
            # Ask user which table to display
            tableName = simpledialog.askstring("Select Table",
                                               "Available tables:\n" + "\n".join(tables) +
                                               "\n\nEnter table name to display:")  # ask for table name and display them
            if tableName and tableName in tables:
                try:
                    columns, rows = getTables(
                        connection, tableName)  # display tables
                    result_text.delete(1.0, tk.END)
                    result_text.insert(
                        tk.END, f"Contents of table '{tableName}':\n\n")
                    # header
                    result_text.insert(tk.END, "\t".join(columns) + "\n")
                    result_text.insert(tk.END, "-"*80 + "\n")
                    # print rows, formatting could be better but whatever
                    for row in rows:
                        result_text.insert(tk.END, "\t".join(
                            [str(item) for item in row]) + "\n")
                except mysql.connector.Error as e:  # general error stuff, wont go over it again since its the same stuff
                    messagebox.showerror(
                        "Error", f"Failed to retrieve table data: {e}")
            else:
                messagebox.showerror(
                    "Invalid Table", "Table not recognized or empty input.")

        elif user_input == "2":  # Display Query Options
            # Show numbered list of friendly query titles
            query_list = [f"{key}: {val['title']}" for key,
                          val in userFriendly.items()]
            query_choice = simpledialog.askstring(
                "Query Options",
                "Available queries:\n" +
                "\n".join(query_list) +
                "\n\nEnter query number to run (1-10):"
            )

            if query_choice and query_choice in userFriendly:
                try:
                    sql = userFriendly[query_choice]["sql"]
                    title = userFriendly[query_choice]["title"]
                    cursor = connection.cursor()
                    cursor.execute(sql)
                    rows = cursor.fetchall()
                    columns = [desc[0] for desc in cursor.description]
                    cursor.close()

                    # Display results
                    result_text.delete(1.0, tk.END)
                    result_text.insert(tk.END, f"{title}\n\n")
                    result_text.insert(tk.END, "\t".join(columns) + "\n")
                    result_text.insert(tk.END, "-"*80 + "\n")
                    for row in rows:
                        result_text.insert(tk.END, "\t".join(
                            [str(item) for item in row]) + "\n")
                except mysql.connector.Error as e:
                    messagebox.showerror("Error", f"Failed to run query: {e}")
            else:
                messagebox.showerror(
                    "Invalid Choice", "Query not recognized or empty input.")

        elif user_input == "3":  # Create New Table
            table_name = simpledialog.askstring(
                "Create Table", "Enter new table name:")
            if table_name:
                columns_def = simpledialog.askstring(
                    "Create Table",
                    "Enter columns and types (e.g., ID INT PRIMARY KEY, Name VARCHAR(50)):"
                )
                if columns_def:
                    try:
                        cursor = connection.cursor()
                        cursor.execute(
                            f"CREATE TABLE {table_name} ({columns_def});")
                        connection.commit()
                        cursor.close()
                        result_text.delete(1.0, tk.END)
                        result_text.insert(
                            tk.END, f"Table '{table_name}' created successfully.\n")
                    except mysql.connector.Error as e:
                        messagebox.showerror(
                            "Error", f"Failed to create table: {e}")
                else:
                    messagebox.showwarning(
                        "Input Required", "Columns definition is required.")
            else:
                messagebox.showwarning(
                    "Input Required", "Table name is required.")

        elif user_input == "4":  # Update Table
            tableName = simpledialog.askstring(
                "Update Table", "Enter table name to update:")
            if tableName:
                columnName = simpledialog.askstring(
                    "Update Table", "Enter column to update:")
                newValue = simpledialog.askstring(
                    "Update Table", "Enter new value:")
                condition = simpledialog.askstring(
                    "Update Table", "Enter condition (e.g., ID=1):")
                if columnName and newValue and condition:
                    try:
                        cursor = connection.cursor()
                        sql = f"UPDATE {tableName} SET {columnName} = '{newValue}' WHERE {condition};"
                        cursor.execute(sql)
                        connection.commit()
                        affected = cursor.rowcount
                        cursor.close()
                        result_text.delete(1.0, tk.END)
                        result_text.insert(
                            tk.END, f"Updated {affected} row(s) in '{tableName}'.\n")
                    except mysql.connector.Error as e:
                        messagebox.showerror(
                            "Error", f"Failed to update table: {e}")
                else:
                    messagebox.showwarning(
                        "Input Required", "All fields are required for update.")
            else:
                messagebox.showwarning(
                    "Input Required", "Table name is required.")

        elif user_input == "5":  # Delete Table Rows
            tableName = simpledialog.askstring(
                "Delete Rows", "Enter table name to delete from:")
            condition = simpledialog.askstring(
                "Delete Rows", "Enter condition for deletion (e.g., ID=1):")
            if tableName and condition:
                try:
                    cursor = connection.cursor()
                    sql = f"DELETE FROM {tableName} WHERE {condition};"
                    cursor.execute(sql)
                    connection.commit()
                    affected = cursor.rowcount
                    cursor.close()
                    result_text.delete(1.0, tk.END)
                    result_text.insert(
                        tk.END, f"Deleted {affected} row(s) from '{tableName}'.\n")
                except mysql.connector.Error as e:
                    messagebox.showerror(
                        "Error", f"Failed to delete rows: {e}")
            else:
                messagebox.showwarning(
                    "Input Required", "Both table name and condition are required.")

        elif user_input == "6":
            messagebox.showinfo("Exit", "Exiting Program")
            root.destroy()
            sys.exit(0)

    # Start the main event loop
    # main window
    root = tk.Tk()
    root.title("Dental Clinic DBMS GUI")
    root.geometry("1000x600")
    #commands and placements
    displayCommands = tk.Label(root, text="Commands:")
    displayCommands.place(x=10, y=10)
    displayDatabase = tk.Label(root, text="1: Display Tables")
    displayDatabase.place(x=10, y=30)
    displayQuery = tk.Label(root, text="2: Display Query Options")
    displayQuery.place(x=10, y=50)
    displayCreate = tk.Label(root, text="3: Create New Table")
    displayCreate.place(x=10, y=70)
    displayUpdate = tk.Label(root, text="4: Update Table")
    displayUpdate.place(x=10, y=90)
    displayDelete = tk.Label(root, text="5: Delete Table")
    displayDelete.place(x=10, y=110)
    displayExit = tk.Label(root, text="6: Exit Program")
    displayExit.place(x=10, y=130)

    # get input from user
    # label to show what the box is for
    entryLabel = tk.Label(root, text="Please Enter Command")
    entryLabel.place(x=425, y=500)

    entry_widget = tk.Entry(root)  # the input box
    entry_widget.place(x=425, y=550)

    result_text = tk.Text(root, width=100, height=25)  # output for many things
    result_text.place(x=200, y=10)
    tk.Button(root, text="Enter", font=("Arial", 11, "bold"),
              command=getCommand).place(x=590, y=525)  # use to get commands and go from there
    root.mainloop()


def runFile(filename, connection):
    cursor = connection.cursor()

    # Read file and split commands correctly (ignoring semicolons inside strings)
    with open(filename, "r", encoding="utf-8") as f:
        sql_script = f.read()

    # Split only on semicolons that are at the end of a line
    commands = re.split(r';\s*(?=\n|$)', sql_script)

    for command in commands:
        command = command.strip()
        if not command:
            continue
        try:
            cursor.execute(command)
            # Consume result sets if any (prevents "Unread result found")
            try:
                _ = cursor.fetchall()
            except mysql.connector.errors.InterfaceError:
                # No results to fetch
                pass
        except mysql.connector.Error as err:
            print(f"SQL Warning: {err}")

    connection.commit()
    cursor.close()


def getTables(connection, table_name):
    cursor = connection.cursor()
    try:
        # Execute query to fetch all data
        cursor.execute(f"SELECT * FROM {table_name};")
        rows = cursor.fetchall()
        columns = [desc[0] for desc in cursor.description]
    except mysql.connector.Error as e:
        cursor.close()
        raise e  # Let the caller handle the error
    cursor.close()
    return columns, rows


def main():
    userGUI()  # create the gui for the user

    # loop through options and stuff till user is done
if __name__ == "__main__":
    main()
